### ISSUE TITLE
Add Instructions for Running Project Locally

### ISSUE THREAD

**Issue by csjones** [bboerst/stratum-work#21]
### Issue Description

I've been trying to get the Stratum Work project running locally, but it's pretty tricky with all the dependencies (RabbitMQ, MongoDB, collectors, and the web app). It would be awesome if we could add some clear instructions to the README on how to set everything up.

### Proposed Solution

Adding a docker-compose setup would make things a lot easier for anyone looking to contribute. This would include all the necessary services and dependencies in one go. Also, it would be great if we could get the README updated with these details too.

### Additional Context

Thanks for considering this! I really appreciate the effort to make the project more accessible to contributors.

**Comment by bboerst** [comment]
Thanks for requesting this, @csjones.

I've been testing #23 on my local machine and it seems to be working fine for me so I'm going to merge this. Feel free to give it a try and let me know if you have any issues. Thanks!
