### ISSUE TITLE
Add PyBLØCK Pool.

### ISSUE THREAD

**Issue by SatoshiNakamotoBitcoin** [bboerst/stratum-work#8]
Solo Pool pool.pyblock.xyz

**Comment by bboerst** [comment]
Thanks for the suggestion!
PyBLOCK is now added.

**Comment by SatoshiNakamotoBitcoin** [comment]
Added #Datum PyBLOCK Templates.

stratum+tcp://pool.pyblock.xyz:23334

**Comment by bboerst** [comment]
Hey @SatoshiNakamotoBitcoin! Sorry for missing this earlier and thanks for tagging me.

`PyBLOCK DATUM` has been added :)
